security:
    encoders:
        AppBundle\Entity\Account: bcrypt

    providers:
        database_users:
            entity: {class: AppBundle:Account, property: username}


    firewalls:

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security_user
            logout:
                path: /logout

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/app/*, roles: IS_AUTHENTICATED_FULLY }
