security:
    encoders:
        AppBundle\Entity\Account: bcrypt

    providers:
        database_users:
            entity: {class: AppBundle:Account, property: username}


    firewalls:
        api:
            pattern: ^/api/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'jwt_token_authenticator'
        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security_user
            logout:
                path: /logout

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
