security:
    encoders:
        AppBundle\Entity\Account: bcrypt

    providers:
        database_users:
            entity: {class: AppBundle:Account, property: username}


    firewalls:
        api:
            pattern: ^/api/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'jwt_token_authenticator'
        main:
            pattern: ^/
            anonymous: ~
            provider: database_users
            form_login:
                # The route name that the login form submits to
                check_path: security_login_check
                login_path: security_login_form

            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                target: /

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
